### ISSUE TITLE
-op parameter generate error 'cell_type_assignments_by_spot.csv does not exist'

### ISSUE THREAD

**Issue by ChangliangWang** [digitalcytometry/cytospace#55]
Dear cytospace developers,

Thanks very much for making such a fantastic tool. When I used the -op parameter, I encounter  the following error.
-op parameter generate error 'cell_type_assignments_by_spot.csv does not exist'

Best regards,
Liang.

**Comment by hsjeon-k** [comment]
Hello Liang,

Thank you for letting us know about the issue! We have updated some of the code for saving files with the -op parameter, and this error should not be present in the updated version. Please update your local installation following the "Updating local installations" part of the documentation, and please let us know if you encounter any further issues!

Best,
Hyun Soo

**Comment by ChangliangWang** [comment]
Hi Hyun Soo,

Thanks very much for your help and update.

Best,
Liang.
