### ISSUE TITLE
Purpose of single cell mode

### ISSUE THREAD

**Issue by reillyeo** [digitalcytometry/cytospace#59]
In the section about running the cytospace tool on single-cell resolution data, it states:

"We highly recommend that an `--st-cell-type-path` (or `-stctp`) be provided when running CytoSPACE in `--single-cell` mode. This file will list the cell type labels for each spot, in the same format as the scRNA-seq cell type labels specified under `--cell-type-path`."

But what is the purpose of running cytospace on this data if the cell types are already known? Is the tool not designed to infer cell types based on a reference (scRNA-seq) dataset?

**Comment by aaronmnewman** [comment]
Thanks for the question. The purpose of running CytoSPACE in single-cell mode is to identify spatially-dependent changes in gene expression within each cell type of interest, while increasing gene recovery from the modest number of genes (a few hundred) typically captured by single-cell ST assays to the higher number of genes typically captured by scRNA-seq (a few thousand). As an example, consider T cells, which typically upregulate exhaustion genes along with other canonical phenotypic states when in close proximity to cancer cells (e.g., see Fig. 2k in the CytoSPACE paper), or macrophages, which are known to upregulate certain factors, such FOLR2, when localized to stromal regions adjacent to the tumor (Extended Data Fig. 10h). The identification of such state changes and others can be facilitated by mapping scRNA-seq data to single-cell ST data. The reason we recommend that users provide a file with a predefined cell type label for each spot is that it is typically straightforward to perform a coarse-grained annotation of major cell types in single-cell ST data, and this ensures that CytoSPACE will map each cell type accordingly (while still providing flexibility to map single-cell transcriptomes within each cell type to locations that reflect their spatial biology). We will edit the single-cell mode section to better describe the purpose of this application. Thanks!
