### ISSUE TITLE
Denoising before running cytoSPACE

### ISSUE THREAD

**Issue by rajeha** [digitalcytometry/cytospace#60]
Thank you for the this great tool! Would you recommend performing denoising with a method such as proposed by in https://www.nature.com/articles/s41467-018-07931-2 before performing cell-type deconvolution with cytoSPACE?

**Comment by hsjeon-k** [comment]
Hello, thank you for the question!

We have not tested CytoSPACE in combination with denoising, so I am personally unsure as to what effect the specific denoising method that you referred to may have on the dataset. However, we have found the performance of CytoSPACE to be robust across different noise conditions, so we expect that denoising will not be necessary for the CytoSPACE run itself.
