### ISSUE TITLE
Unexpected Terminated when Solving linear assignment problem

### ISSUE THREAD

**Issue by QianhuiXu** [digitalcytometry/cytospace#61]
Hello,

cytospace is a wonderful tool！

I ran into an issue with explore my scRNA and ST data.

My command : 
cytospace -sp scRNA_08_counts.txt -ctp scRNA_08_celllabel.txt -stp stRNA08_counts.txt -cp stRNA08_coordinates.txt -o cytospace_results_08 -sm lap_CSPR

Error:
(cytospace) shpc_100668@shpc52:~/liverzonation/cytospace/data/liver$ cytospace -sp scRNA_08_counts.txt -ctp scRNA_08_celllabel.txt -stp stRNA08_counts.txt -cp stRNA08_coordinates.txt -o cytospace_results_08 -sm lap_CSPR
Read and validate data ...
100% |██████████████████████████████████████████████████| Reading data [done]
Estimating cell type fractions
2023-03-11 14:53:27 Load ST data
PC_ 1
Positive:  IGHG4, IGKC, IGHG3, TAGLN, MYL9, CRIP1, FLNA, C7, VIM, S100A6
           IGHGP, MYH11, ACTA2, AEBP1, JCHAIN, ADIRF, IGLC2, MGP, IGHG1, CD74
           TPM2, IGHA1, TMSB10, TMSB4X, IGFBP7, SPARCL1, FBLN1, GSN, HLA-DRB1, IGFBP5
Negative:  APOA1, APOC3, HP, APOC1, APOA2, ORM1, FGB, CYP3A4, CYP2E1, VTN
           ITIH4, SERPINF2, ADH1A, AL645922.1, SCD, MT2A, AGXT, RIDA, CYP2C8, FTCD
           MT1G, ASS1, AGT, APOC4, FABP1, F2, HAMP, DHCR24, IGFBP4, CYP1A2
PC_ 2
Positive:  IGHG4, IGHG3, IGKC, IGHGP, IGHG1, IGLC2, JCHAIN, IGHA1, IGLL5, APOA1
           IGHM, IGHG2, MZB1, IGLC3, APOC3, APOC1, APOA2, C7, HP, FGB
           CYP2E1, ORM1, INMT, F2, FABP1, IGHA2, VTN, SERPINF2, AGXT, ITIH4
Negative:  TFF2, MUC5B, SCGB3A1, TFF3, TFF1, MUC1, CEACAM6, FXYD2, LGALS2, SPINK1
           LYZ, CD24, PIGR, C19orf33, ANXA4, SLC44A4, DUOX2, S100A6, TCN1, AGR2
           AKR1B10, NQO1, CRISP3, GABRP, GPX2, KRT19, FXYD3, APCDD1, SPP1, SMIM24
PC_ 3
Positive:  IGHG4, IGHG3, IGKC, IGHGP, TFF2, MUC5B, IGHG1, IGLC2, SCGB3A1, TFF3
           JCHAIN, FXYD2, TFF1, MUC1, CEACAM6, IGHA1, SPINK1, LGALS2, LYZ, CD24
           PIGR, ANXA4, IGHM, SLC44A4, C19orf33, IGLL5, DUOX2, TCN1, IGHG2, AGR2
Negative:  TAGLN, MYL9, FLNA, CRIP1, MYH11, ACTA2, TPM2, ADIRF, DES, SPARCL1
           AC006254.1, VIM, AEBP1, CSRP1, IGFBP5, CAVIN1, ACTG2, MFGE8, MYL6, CNN1
           MGP, LMOD1, DSTN, TNS1, CKB, MCAM, CRIP2, MUSTN1, CCDC3, CAV1
PC_ 4
Positive:  IGHG4, MYL9, IGHG3, TAGLN, DES, MYH11, IGHGP, FLNA, TFF2, MUC5B
           TFF1, TPM2, ACTA2, SCGB3A1, MUC1, ACTG2, CSRP1, CEACAM6, SPINK1, CNN1
           LMOD1, TFF3, PIGR, CKB, DUOX2, AC006254.1, AKR1B10, CRISP3, C19orf33, DSTN
Negative:  CD74, CCL19, TMSB4X, TMSB10, HLA-DRB1, HLA-DRA, C7, RPS27, HLA-DPB1, HLA-DQB1
           PTGDS, IGHM, IGHA1, HLA-DPA1, CCL21, RPLP2, TIMP1, RPS19, CD52, MGP
           RPS18, VIM, RPL13, LAPTM5, RPS12, RPL27A, IGFBP7, FBLN1, RPS15, RPL13A
PC_ 5
Positive:  IGKC, IGHA1, JCHAIN, IGHG1, IGHM, IGLC2, MYL9, IGLC3, IGHA2, TAGLN
           MZB1, IGLL5, DES, MYH11, MUC5B, ACTG2, CYP3A4, LMOD1, TFF2, TFF1
           MUC1, CSRP1, CNN1, TPM2, CYP2E1, FLNA, DUOX2, IGFBP5, CKB, HSPB6
Negative:  IGHG4, IGHG3, IGHGP, CD74, CCL19, TMSB4X, TMSB10, HLA-DRB1, RPS27, HLA-DPB1
           TIMP1, CCL21, HLA-DRA, PTGDS, RPS18, S100A6, VIM, HLA-DQB1, CD52, CXCR4
           LAPTM5, RPLP2, HLA-DPA1, RPS19, ACTB, RPL13, TRBC1, RPLP1, MGP, CCR7
2023-03-11 15:09:37 Load scRNA data
Warning: Invalid name supplied, making object name syntactically valid. New object name is Cell.IDsCellType; see ?make.names for more details on syntax validity
PC_ 1
Positive:  PTPRB, LDB2, DNASE1L3, ST6GAL1, RELN, STAB2, LIFR, NPL, NTN4, MEIS2
           LINC02388, NRG3, CD36, HECW2, GPM6A, ANKS1A, CRHBP, ST6GALNAC3, AC098650.1, MRC1
           FBXL7, FCHSD2, PLCB1, AKAP12, PLXDC2, MS4A6A, ITGA9, BMPER, NRP1, PPFIBP1
Negative:  CYP3A5, ACSM2A, CYP2C8, AFM, ACSM2B, C3, TAT, CYP2B6, CYP2C9, GHR
           FTCD, TF, MAT1A, ECHDC2, PLG, AL583836.1, FMO5, SCP2, CPS1, CUX2
           APOB, ZC3H13, CP, HSP90AA1, ALB, AC011604.2, ACSL1, DPYS, PCSK6, BHMT
PC_ 2
Positive:  ADAMTSL1, CCBE1, AC098650.1, COL25A1, PRKG1, PTH1R, HHIP, DACH1, ADAMTS13, ANK3
           SYT1, LAMA2, ZFPM2, RIPOR3, AF165147.1, NR1H4, FGFR2, GRK5, LINC02398, HMCN1
           ADAMTS2, ANKS1A, SGCZ, CNTN4, PDE1A, PLA2G5, ARHGAP15, CALD1, PCDH9, LAMB1
Negative:  PTPRB, LDB2, DNASE1L3, ST6GAL1, STAB2, NPL, NTN4, CD36, NRG3, MRC1
           CRHBP, HECW2, ST6GALNAC3, AKAP12, MS4A6A, FCHSD2, PPFIBP1, MEIS2, LINC02388, STAB1
           RIPOR2, SLC26A5, PTPRT, LGMN, KALRN, ACSM3, SEMA6A, XAF1, F8, ADGRF5
PC_ 3
Positive:  ANXA4, PKHD1, BICC1, RALYL, CTNND2, DCDC2, KCNJ15, CFTR, WNK2, PDGFD
           FGFR2, MAML2, CASR, CALN1, DSCAML1, LINC01320, SLC5A1, AC008554.1, SLC4A4, TM4SF4
           FRAS1, PLD1, CASC15, SLC12A2, SLC17A4, TMTC2, ROCR, GLIS3, KRT7, CHST4
Negative:  CYP3A5, ACSM2A, CYP2C8, AFM, ACSM2B, C3, TAT, CYP2B6, CYP2C9, GHR
           NEAT1, TF, PLG, RELN, MAT1A, CPS1, PCSK6, TMEM56, CP, SCP2
           CUX2, APOB, FTCD, BHMT, ACSL1, C1R, CCBE1, PDE3B, ECHDC2, NSUN6
PC_ 4
Positive:  DNASE1L3, NPL, STAB2, RELN, NTN4, MS4A6A, ANXA4, MRC1, CRHBP, AKAP12
           STAB1, PKHD1, LGMN, ST6GAL1, NRP1, MYO10, HECW2, BICC1, PPFIBP1, ANKS1A
           SLC26A5, ADGRL2, PTPRT, HS3ST3A1, OIT3, FGFR2, CLEC4M, CPM, ANKRD44, CTTNBP2
Negative:  MECOM, ST8SIA6, ANO2, TMTC1, VWF, SPARCL1, PECAM1, SULF1, ELN, LDB2
           PTPRB, PLCXD3, FAM155A, ARL15, SLCO2A1, PLCB4, COL8A1, FLRT2, ENTPD1, MMP28
           DOCK9, RYR3, NAV3, HEG1, ST6GALNAC3, OPCML, PTGIS, TANC2, CDH11, RUNX1T1
PC_ 5
Positive:  RBFOX1, CTNNA2, PCDH15, CNTNAP2, EYS, ASIC2, GALNTL6, CCDC26, AGBL4, GRID2
           NRXN1, NRXN3, LRRC4C, AC007402.1, DPP6, LINC00276, NPL, CDH12, CSMD1, CACNA1A
           CDH18, PTPRT, CFAP299, AL589740.1, DGKB, ERC2, NELL1, CNTNAP5, DOCK3, AC011287.1
Negative:  MECOM, PTPRB, LDB2, ST8SIA6, FLRT2, ANXA4, ARL15, SPARCL1, CYP3A5, SULF1
           ANO2, PLCXD3, MEIS2, PECAM1, PKHD1, TMTC1, BICC1, PLPP1, SLCO2A1, VWF
           ST6GALNAC3, HSP90AA1, FGFR2, ELN, NR2F2-AS1, PTPRG, RUNX1T1, PTPN14, MMP28, PTGIS
2023-03-11 15:13:36 Integration
Performing PCA on the provided reference using 2875 features as input.
Projecting PCA
Finding neighborhoods
Finding anchors
        Found 6322 anchors
Filtering anchors
        Retained 1454 anchors
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
100% |██████████████████████████████████████████████████| Reading data [done]
Time to read and validate data: 2877.4 seconds
Estimating number of cells in each spot ...
Time to estimate number of cells per spot: 416.89 seconds
Down/up sample of scRNA-seq data according to estimated cell type fractions
Time to down/up sample scRNA-seq data: 17.6 seconds
Building cost matrix ...
Time to build cost matrix: 3448.55 seconds
Solving linear assignment problem ...
Terminated

I'm really at a loss as to how to proceed, and any guidance would be much appreciated!
Thank you for your kind help!

**Comment by hsjeon-k** [comment]
Hello, thank you for letting us know!

From the runtime logged on your error message, it seems like you may be running CytoSPACE with a large dataset. In this case, the process might be getting terminated/killed due to memory restrictions. I would suggest trying the subsampling option to reduce the memory requirement, where your ST dataset will be partitioned into smaller chunks for assigning single cells. Please see the "Advanced options - Spot subsampling for parallelization" section of the documentation for more information.

The required flags will be: `cytospace [...] -sss -nosss [number_of_ST_cells_in_each_partition] -nop [number_of_processors]` (please note that `-nosss` is different from `-noss`, which is not relevant in this case). 
I find that for the example breast cancer dataset, `-sss -nosss 3000 -nop 2` works well on my local environment with ~8GB RAM. But the sufficient `-nosss` and `-nop` combination would really depend on your dataset size and environment setup, so I would suggest that you experiment with different values (using the highest possible `-nosss` that can run without going out of memory would be the most effective).

When using the `-nop` flag, you might get a different error message for going out of memory -- in my case, I usually see `concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.` which I resolve by choosing a lower `-nosss`.
