### ISSUE TITLE
can't install, plz help me 

### ISSUE THREAD

**Issue by wanglin1992** [digitalcytometry/cytospace#64]
ERROR: Cannot determine archive format of C:\Users\\AppData\Local\Temp\pip-req-build-0kk1ri9z

**Comment by hsjeon-k** [comment]
Hello! Could you let us know which command you are using to install the package?

You can:
(1) clone the repository with `https://github.com/digitalcytometry/cytospace.git`
(2) move into the new "cytospace" directory with `cd cytospace`
(3) install it with `pip install .`
