### ISSUE TITLE
How to specify a 'genome' parameter?

### ISSUE THREAD

**Issue by psenin-sanofi** [digitalcytometry/cytospace#65]
Hi guys -- I'm running CytoSPACE on a 10x visium space ranger output and getting the following error:

```
Read and validate data ...
Traceback (most recent call last):
  File "/opt/conda/envs/cytospace/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/opt/conda/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 683, in run_cytospace
    main_cytospace(**arguments)
  File "/opt/conda/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 520, in main_cytospace
    read_data(scRNA_path, cell_type_path,
  File "/opt/conda/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 19, in read_data
    st_data, coordinates_data = read_visium(spaceranger_path,output_path)
  File "/opt/conda/envs/cytospace/lib/python3.8/site-packages/cytospace/common/common.py", line 50, in read_visium
    visium_adata = sc.read_visium(count_dir,count_file=fin_count)
  File "/opt/conda/envs/cytospace/lib/python3.8/site-packages/scanpy/readwrite.py", line 360, in read_visium
    adata = read_10x_h5(path / count_file, genome=genome)
  File "/opt/conda/envs/cytospace/lib/python3.8/site-packages/scanpy/readwrite.py", line 196, in read_10x_h5
    adata = _read_legacy_10x_h5(filename, genome=genome, start=start)
  File "/opt/conda/envs/cytospace/lib/python3.8/site-packages/scanpy/readwrite.py", line 209, in _read_legacy_10x_h5
    raise ValueError(
ValueError: '/home/xxx_sr/molecule_info.h5' contains more than one genome. For legacy 10x h5 files you must specify the genome if more than one is present. Available genomes are: ['barcode_idx', 'barcode_info', 'barcodes', 'count', 'feature_idx', 'features', 'gem_group', 'library_idx', 'library_info', 'metrics_json', 'umi', 'umi_type']
```
What exactly should I specify to get past this? My genome is GRCh38 ...

Thanks!

**Comment by hsjeon-k** [comment]
Hello, thank you for the question!

It looks like the error is related to the `scanpy.read_10x_h5` call made internally, to which CytoSPACE currently does not pass in any value for the "genome" parameter.

As an alternative for now, you can convert your Space Ranger output into an ST gene expression and an ST coordinate file, and pass them into CytoSPACE with the `--st-path` (`-stp`) and `--coordinates-path` (`-cp`) flags, respectively. You can use the [R helper script](https://github.com/digitalcytometry/cytospace/blob/main/cytospace/Prepare_input_files/generate_cytospace_input_from_spaceranger_output.R) that we provide for doing this.

Starting from the tarball that you are using as input, the script can be invoked as follows:
(1) Inside the cytospace conda environment, run `conda install -c conda-forge r-hdf5r`, as the script requires an additional dependency.
(2) Unzip the tarball -- this can be done with `tar -xvzf [name_of_sr_output].tar.gz`, which will create a directory called `[name_of_sr_output]` with the contents.
(3) Please rename the gene expression H5 file to `filtered_feature_bc_matrix.h5` -- this should allow the script to work without any further edits to the code.
(4) Invoke the script with `Rscript generate_cytospace_input_from_spaceranger_output.R [name_of_sr_output] [output_directory]`. This should create the files `ST_data.csv` and `Coordinates.csv` under `[output_directory]` (of your choice).
(5) You can now substitute the `--spaceranger-path [name_of_sr_output].tar.gz` part of your command with `--st-path [output_directory]/ST_data.csv --coordinates-path [output_directory]/Coordinates.csv`.

Thank you once again for letting us know about the issue! We will consider what we can do about similar cases going forward.
