### ISSUE TITLE
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):

### ISSUE THREAD

**Issue by zt6597** [digitalcytometry/cytospace#68]
Hi cytoSPACE team:
Thanks to your wonderful work, yet i met some issues as following: 
_______________________________________________________________________________________
cytospace \
> --scRNA-path 'scRNA_data.txt' \
> --cell-type-path 'cell_type_labels.txt' \
> --st-path 'ST_data.txt' \
> --coordinates-path 'Coordinates.txt' \
> --solver-method lapjv
No protocol specified
Read and validate data ...
100% |██████████████████████████████████████████████████| Reading data [done]
Estimating cell type fractions
WARNING: ignoring environment value of R_HOME
Warning message:
package ‘argparse’ was built under R version 4.2.0 
Warning message:
package ‘data.table’ was built under R version 4.2.1 
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/media/whc/02C401E8C401DF33/zt/R/x86_64-pc-linux-gnu-library/4.2/rlang/libs/rlang.so':
  /media/whc/02C401E8C401DF33/zt/R/x86_64-pc-linux-gnu-library/4.2/rlang/libs/rlang.so: undefined symbol: EXTPTR_PROT
In addition: Warning message:
package ‘Seurat’ was built under R version 4.2.1 
Execution halted
Traceback (most recent call last):
  File "/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 683, in run_cytospace
    main_cytospace(**arguments)
  File "/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 520, in main_cytospace
    read_data(scRNA_path, cell_type_path, 
  File "/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 35, in read_data
    cell_type_fraction_estimation_path = estimate_cell_type_fractions(scRNA_path, cell_type_path, st_path, output_path, output_prefix)
  File "/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/lib/python3.8/site-packages/cytospace/common/common.py", line 80, in estimate_cell_type_fractions
    out = subprocess.run(run_args, check=True)
  File "/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/lib/python3.8/site-packages/cytospace/get_cellfracs_seuratv3.R', '--scrna-path', 'scRNA_data.txt', '--ct-path', 'cell_type_labels.txt', '--st-path', 'ST_data.txt', '--outdir', '/media/whc/12T/ZT/steroseq/cytoSPACE nom1d/cytospace_results', '--prefix', '']' returned non-zero exit status 1.
____________________________________________________________
Can u plz help me with this? Many thanks.

**Comment by hsjeon-k** [comment]
Hello, thank you for the question!

This might have something to do with the version of R and the packages that we are importing in the process.
Could you let us know which version of R and Seurat you have in the CytoSPACE environment? You can see this by running `conda list r-base` and `conda list r-seurat` from the command line, inside the CytoSPACE environment.

Personally, I have R 4.0.5 running with Seurat 3.2.3. Considering that you are also getting warnings for other packages (`argparse` and `data.table`) as well, I think the R version may be an issue.

**Comment by zt6597** [comment]
> Hello, thank you for the question!
> 
> This might have something to do with the version of R and the packages that we are importing in the process. Could you let us know which version of R and Seurat you have in the CytoSPACE environment? You can see this by running `conda list r-base` and `conda list r-seurat` from the command line, inside the CytoSPACE environment.
> 
> Personally, I have R 4.0.5 running with Seurat 3.2.3. Considering that you are also getting warnings for other packages (`argparse` and `data.table`) as well, I think the R version may be an issue.

Thanks for your replay!
My R and seurat version are:
# packages in environment at /media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace:
# Name                    Version                   Build  Channel
r-base                    4.0.5                hb87df5d_8    conda-forge
r-base64enc           0.1_3           r40hcfec24a_1004    conda-forge
r-seurat                  3.2.3             r40h03ef668_0    conda-forge

**Comment by hsjeon-k** [comment]
Hello, thank you for the response!

It looks like you have the same versions of the software installed as I do.
However, CytoSPACE's internal call to Rscript seems to be pointing to a different version of R that you also have access to -- this is probably a system-wide version that you have, separate from the conda installation. We will look into whether there is a better way of calling Rscript internally. 

The error is only relevant to a preliminary step where CytoSPACE attempts to estimate the fractional composition of each cell type in the ST dataset. As a workaround for now, you can run this step separately (please see below), or provide your own estimate file (please see the _Advanced Options - User-provided fractional composition of each cell type_ section of the [documentation](https://github.com/digitalcytometry/cytospace/blob/main/README.md)).

If you would like to run this step separately:

(1) Run `whereis Rscript` inside the cytospace conda environment, to find the full path to the correct version of Rscript.
  - This command will list paths to all versions of Rscript that you have access to. In your case, you will likely have two or more paths listed.
  - The one you are looking for probably has "cytospace" somewhere in the path -- in your case, I think it might be `/media/whc/02C401E8C401DF33/zt/.local/share/r-miniconda/envs/cytospace/bin/Rscript` or something similar.

(2) `cd /path/to/cytospace/`: move inside your CytoSPACE directory

(3) Using the full path to Rscript from above, run `/path/to/Rscript cytospace/get_cellfracs_seuratv3.R --scrna-path [scRNA_expr_file] --ct-path [scRNA_cell_type_file] --st-path [ST_expr_file] --outdir [output_dir] --prefix [output_prefix]`
  - This will run the R script using the correct version of R.
  - In the output directory, it will generate a file named `[output_prefix]Seurat_weights.txt`. This is the estimated cell type fraction.

(4) You can re-run CytoSPACE with the `-ctfep` parameter added: `cytospace [all other parameters as required] -ctfep /path/to/[output_prefix]Seurat_weights.txt`
  - This will do the same thing as your original CytoSPACE call, but will bypass the internal call to Rscript as you are providing the required file.

Thank you once again for letting us know about the issue. Please let us know if this works!

**Comment by zt6597** [comment]
> > 
> 
> Many thanks for your detailed reply ! I have followed your codes to run get_cellfracs_seuratv3 in cloning into cytospace path, Yet i got the same error as before:
> 
> conda activate cytospace cd /home/whc/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace Rscript get_cellfracs_seuratv3.R \
> 
> > --scRNA-path '/media/whc/12T/ZT/steroseq/cytoSPACE nom1d/scRNA_data.txt' 
> > --cell-type-path '/media/whc/12T/ZT/steroseq/cytoSPACE nom1d/cell_type_labels.txt' 
> > --st-path '/media/whc/12T/ZT/steroseq/cytoSPACE nom1d/ST_data.txt' 
> > --coordinates-path '/media/whc/12T/ZT/steroseq/cytoSPACE nom1d/Coordinates.txt' 
> > --outdir '/media/whc/12T/ZT/steroseq/cytoSPACE nom1d/' 
> > --prefix 'nom1d'
> > WARNING: ignoring environment value of R_HOME
> > Warning message:
> > package ‘argparse’ was built under R version 4.2.0
> > Warning message:
> > package ‘data.table’ was built under R version 4.2.1
> > Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
> > unable to load shared object '/media/whc/02C401E8C401DF33/zt/R/x86_64-pc-linux-gnu-library/4.2/rlang/libs/rlang.so':
> > /media/whc/02C401E8C401DF33/zt/R/x86_64-pc-linux-gnu-library/4.2/rlang/libs/rlang.so: undefined symbol: EXTPTR_PROT
> > In addition: Warning message:
> > package ‘Seurat’ was built under R version 4.2.2
> > Execution halted

**Comment by hsjeon-k** [comment]
Hello, thank you for the response, and sorry to hear that there was another error.

Just to make sure whether this is an issue with the version of R itself or the R packages. could you confirm the following:
After `conda activate cytospace`, `Rscript --version` gives you R 4.0.5, and `which Rscript` gives you a path under the CytoSPACE environment directory (likely something along the lines of `[...]/envs/cytospace/bin/Rscript`).

If this is not the case, then `Rscript` is not calling the correct version of R, and the `Rscript` term in your command should be substituted with the full path to the Rscript executable (which you checked in step 1, with `whereis Rscript` -- e.g., the full command should be `/path/to/Rscript get_cellfracs_seuratv3.R [arguments]`).

If it does give you R 4.0.5 that came with CytoSPACE, then I actually might suggest trying uninstalling/reinstalling CytoSPACE. It seems that for some reason there is a mismatch between the R version and the package versions -- the version of Seurat installed with CytoSPACE should be built with R 4.0.3, while the warning message says 4.2.2. I suspect that something might have gone wrong during installation in terms of referencing paths.

Thank you! I hope this helps, but of course please let us know if you keep running into an error!
