### ISSUE TITLE
Issues about parameter 'ctfep'

### ISSUE THREAD

**Issue by wangzlgithub** [digitalcytometry/cytospace#69]
Hi!
I have a question about the parameter `-ctfep`.
For deconvolution tools, they usually return a spot*celltype matrix. But in your `-ctfep` description, there are only two rows that one is celltype, and the other is fractions.

Can I think it is summing all spots and then calculating the proportion of each celltype?

**Comment by hsjeon-k** [comment]
Hi!
Yes, you are correct -- if you are specifying the `-ctfep` parameter, the file should contain proportions of each cell type across the entire spatial transcriptomics sample.
