### ISSUE TITLE
Error arised in plot.py--TypeError: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by hiiiyilingzhang** [digitalcytometry/cytospace#70]
Hii CytoSpace team!

Happy to get on board and try the software. I encountered an error when plotting when using v1.0.2: 

```
Traceback (most recent call last):
  File "/home/yiling/mambaforge-pypy3/envs/ST-cytospace/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/home/yiling/mambaforge-pypy3/envs/ST-cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 683, in run_cytospace
    main_cytospace(**arguments)
  File "/home/yiling/mambaforge-pypy3/envs/ST-cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 675, in main_cytospace
    plot_results(output_path, output_prefix, coordinates_data=coordinates_data, geometry=geometry, max_num_cells=max_num_cells_plot)
  File "/home/yiling/mambaforge-pypy3/envs/ST-cytospace/lib/python3.8/site-packages/cytospace/post_processing/plot.py", line 337, in plot_results
    plot_results_bulk_ST_by_spot(coordinates_data, metadata, output_directory, output_prefix, geometry=geometry, num_cols=num_cols)
  File "/home/yiling/mambaforge-pypy3/envs/ST-cytospace/lib/python3.8/site-packages/cytospace/post_processing/plot.py", line 61, in plot_results_bulk_ST_by_spot
    y_int = np.median(np.unique(np.diff(np.sort(np.unique(Y)))))
  File "<__array_function__ internals>", line 180, in diff
  File "/home/yiling/mambaforge-pypy3/envs/ST-cytospace/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1447, in diff
    a = op(a[slice1], a[slice2])
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

It seems like the data type problem related to numpy. Could you please drop some hints for the issue? Much appreciated to your creative and committed work!

Bests,
Elaine

**Comment by hsjeon-k** [comment]
Hi, thank you for the question!

It looks like the spot coordinates are being interpreted as strings rather than numeric values.
This might happen if there are non-numeric values for row/col values inside the file provided under `--coordinates-path` (`-cp`). Would it be possible for you to check whether your input coordinate file contains non-numeric values?

If this is not the case, please let us know!

Best,
Hyun Soo

**Comment by hiiiyilingzhang** [comment]
Hi Hyun Soo,

Sorry I didn't mention my input file format. I use `--spaceranger-path` to fetch output from spaceranger v2.0.1. The `tissue_positions.csv` be like:

```
$ column -s, -t < tissue_positions.csv | head -n 10 
barcode             in_tissue  array_row  array_col  pxl_row_in_fullres  pxl_col_in_fullres
ACGCCTGACACGCGCT-1  1          0          0          387                 489
TACCGATCCAACACTT-1  1          1          1          450                 526
ATTAAAGCGGACGAGC-1  1          0          2          387                 562
GATAAGGGACGATTAG-1  1          1          3          450                 598
GTGCAAATCACCAATA-1  1          0          4          387                 635
TGTTGGCTGGCGGAAG-1  1          1          5          450                 671
GCATCCTCTCCTATTA-1  1          0          6          387                 708
GCGAGGGACTGCTAGA-1  1          1          7          451                 744
TGGTACCGGCACAGCC-1  1          0          8          387                 780
```

I alternatively switched to `-stp` and `-cp` input format and it works! My guess is that from spaceranger v2.0.0, they [added header row](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/release-notes), so it might cause some problems in `scanpy.read_visium` when reading coordinate file?

Also, may I know if I need to generate `Coordinates.csv` files from `spaceranger` output by code, which coordination should I extract? According to 10X [tutorial](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/spatial), `array_row` and `array_col` means coordinate of the spot in the array, `pxl_row_in_fullres` and `pxl_col_in_fullres` are pixel coordinate of the center of the spot in the full resolution image. And it's really confuse me.

Bests,
Elaine

**Comment by hsjeon-k** [comment]
Hi Elaine,

Thank you so much for the detailed pointers!
Yes, I think using the current version of `scanpy.read_visium` for SpaceRanger v2.0.0+ outputs may have caused some issues.
It looks like the Scanpy team very recently added the support for this exact issue on their GitHub repo, but it probably has not been integrated into a new release yet.
For now, I think your workaround of using `-stp` and `-cp` should work well. We will also consider whether we can add anything on our side to account for the version changes.

Regarding the row/col values, your choice of which values to use should not affect the plots or single-cell assignments with CytoSPACE, as we try to take into account which type of coordinates you are using.
Using `pxl_row_in_fullres` and `pxl_col_in_fullres` may make it easier for you to access the scaled coordinates in your downstream analysis, but please feel free to use the ones that better fits in with your workflow.

Thank you, and please let us know if you have any other questions!

Best,
Hyun Soo
