### ISSUE TITLE
Error during get_cellfracs_seuratv3.R - colSums(predictions.assay) :    'x' must be an array of at least two dimensions

### ISSUE THREAD

**Issue by ssrin2** [digitalcytometry/cytospace#71]
Hello,

Thank you for this great tool! When I try to deploy cytospace using a space ranger .h5 file for the st input and a matrix for the sc reference, the pipeline runs fine until the  get_cellfracs_seuratv3.R  step. It appears that the error is occurring towards the end of the script here : 

  ```
col_sums <- colSums(predictions.assay)
  cellfrac <- col_sums / sum(col_sums)
```

I get the following error: 

```
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
Error in colSums(predictions.assay) : 
  'x' must be an array of at least two dimensions
Calls: get_cellfracs_seuratv3 -> colSums
Execution halted
```

Could you please advice on how to correct this? Thank you so much!

**Comment by hsjeon-k** [comment]
Hello, thank you for the question!

The possible cases that immediately come to mind are:
(1) There is only a single cell type present in the scRNA cell type file
(2) The cell IDs in the scRNA expression and cell type files do not match

But both of these cases seem highly unlikely. I am having a hard time reproducing the error -- would it be possible for you to provide a set of input files that leads to this error (on this thread, or at cytospaceteam@gmail.com)? Even a subset or a demo file would be helpful for us to pinpoint the cause of the error.

Thank you so much!
