### ISSUE TITLE
comparing different dlides/sections

### ISSUE THREAD

**Issue by gebdu** [digitalcytometry/cytospace#75]
Hi,

This is such a nice package.
I have 2 visium slides from brain each with 4 sections. So, 8 samples to compare.
We I am running each section individually, would it be comparable later? Can we do DE analysis between two slides or two sections from same slide?

How to follow DE analysis from here? Any tutorial?

thanks

**Comment by hsjeon-k** [comment]
Hi, thank you for your interest in CytoSPACE.

Running the tool on each sample individually will give you the optimal cell-to-spot assignment inside each sample, based on the given single-cell and spatial transcriptomics data.
However, CytoSPACE may be one part of your processing pipeline, and I believe the comparability of multiple slides or the choice of methods for DE analysis may depend more on the characteristics of your dataset and your desired downstream application, so I may not be able to give a concrete answer on this point.

Thank you!
