### ISSUE TITLE
Error: Cannot find more nearest neighbours than there are points

### ISSUE THREAD

**Issue by kwangdol** [digitalcytometry/cytospace#79]
Hello CytoSPACE team:
Thanks to your wonderful work, yet i met some issues as following:

$ cytospace -sp ONE_scRNA_data.txt -ctp ONE_cell_type_labels.txt -stp ONE_ST_data.txt -cp ONE_Coordinates.txt &
[1] 1125807
$ Read and validate data ...
Estimating cell type fractions
2023-08-01 18:24:35 Load ST data
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
PC_ 1 
Positive:  HSPA5, PDIA4, TMED2, MANF, CALR, BHLHA15, P4HB, TMED9, LMAN1, SLC3A2 
           FTL, FAM114A1, SDF2L1, SERP1, DNAJB9, HERPUD1, CANX, SEL1L, HYOU1, CLDN4 
           SURF4, SND1, MLEC, CRELD2, POLR3D, ANKRD37, SYVN1, SEC61A1, TXNDC5, DNAJB11 
Negative:  SOD2, S100A6, TFPI2, IL1B, SPP1, C3, ACTB, SAT1, TPM1, BST2 
           GSTP1, IGFBP7, TGM2, MMP7, COL7A1, IFI44L, PDZK1IP1, MT2A, BEX3, LAMC2 
           IFI6, ITGB3, IFITM1, CXCL5, RARRES2, LCN2, TRIM22, ANXA4, IL4I1, ITGB6 
PC_ 2 
Positive:  PLEC, CYP1B1, DAPK1, TUBA4A, INAVA, TSC22D4, PMEPA1, NUP42, SYNE2, G0S2 
           CAMSAP3, LASP1, VASP, NTN4, INPPL1, A4GALT, ATP2A2, VIM, CNPY2, SMARCC2 
           EIF2AK4, KANK2, RNF31, ARF3, MBOAT7, PES1, TNFRSF11B, RNF10, ZFP36L1, RBMS2 
Negative:  HILPDA, PFKFB3, ANKRD37, IL6, DDIT4, JUNB, MACC1, ERRFI1, JUN, CXCR4 
           ADM, ID2, RHOB, IFIT3, MAFK, ISG20, ISG15, SLC25A37, PLIN2, HIST1H1E 
           TP53BP2, TNFSF10, UGCG, H1F0, F3, LGALS3, HSP90B1, IGFBP3, HERC5, PDIA4 
PC_ 3 
Positive:  COL6A2, COL6A1, MMP1, DCN, SERPINB2, FBN1, MMP3, MME, COL6A3, FTL 
           INHBA, RCAN1, CXCL8, SPARC, TMEM158, EGR1, VIM, IL11, AHRR, TIMP3 
           TRAF3IP2, ARCN1, LOX, CD68, MYADM, CTSL, TIMP1, SYVN1, ATP5IF1, MARCKS 
Negative:  HSPA1B, MYO6, CLIP4, PADI1, HSP90AA1, CGN, SLPI, SRRT, CBX3, IER5 
           PROSER2, TMEM63A, MAL2, GDA, ENO2, PNRC2, PPP1R15B, SLC25A3, GATA6, TMSB4X 
           ANKRD37, SOX13, RAB3IP, GPRC5A, PAQR3, PTPN12, THOC6, CLDN4, CYLD, LAMA5 
PC_ 4 
Positive:  LCN2, MUC1, ANXA4, NCOA7, TRIM2, TNFAIP2, SHTN1, ARRDC3, STAT2, ALDH18A1 
           COA4, HOXB3, IGFBP3, TTC37, C15orf48, PROM1, FNDC3A, MMP7, ESRP1, DDX60L 
           DNAJB11, CP, GSTP1, TPM1, ALOX5, ST5, TMEM129, SAA2, SYTL1, COL4A2 
Negative:  RCAN1, MMP1, MMP3, G0S2, SERPINB2, ANGPTL4, CCDC71L, CXCL8, JARID2, F3 
           MT2A, LAMA3, JUN, TM4SF1, SEMA7A, SMTN, CGGBP1, ATG101, SERPINE1, IL1B 
           SAMD8, CHD2, IL11, TMEM158, TSC22D2, ITGA5, ADM, SIPA1, HSPH1, LRRFIP1 
PC_ 5 
Positive:  RSAD2, ATF3, PLAUR, ISG15, B2M, C15orf48, WARS, IFI27, ZNFX1, HELZ2 
           IFI6, IL15RA, CCL5, PMAIP1, LAMC2, FAM210A, PKIG, IER5, RHOF, ZNF165 
           CST6, LARP4B, IDO1, SART3, HERC5, FNIP1, UBAP2L, PAF1, CALR, MTMR1 
Negative:  ERRFI1, SLC25A37, PFKFB3, HILPDA, CPT1B, CXCR4, DDIT4, SPON1, ANGPTL4, ANP32E 
           ANKZF1, ARRDC3, NPC1, LAMA5, BDKRB1, MYO6, HOXB6, ADSSL1, TMEM165, LOX 
           POLG, MARCKS, C4orf48, FNBP4, SYNE2, REXO4, OBSL1, NME3, MAPK15, FCHO2 
2023-08-01 18:24:40 Load scRNA data
Warning: Invalid name supplied, making object name syntactically valid. New object name is Cell.IDsCellType; see ?make.names for more details on syntax validity

$ PC_ 1 
Positive:  KRT19, EPCAM, SPINT2, SLPI, FXYD2, CALB1, KRT7, CD24, SPP1, PDZK1IP1 
           RNASET2, TSPAN1, CLDN3, CLDN7, C19orf33, MMP7, KRT8, EZR, UCA1, LCN2 
           APOL1, SPINT1, CLDN4, LAMC2, KRT18, VAMP8, LINC02582, CLDN1, LAMB3, ATP1B1 
Negative:  COL3A1, SERPINE2, COL1A2, COL1A1, IGFBP5, CEMIP, IGFBP2, COL6A3, HSPA1A, FBLN1 
           CCL2, TNC, APOE, MFAP4, CPE, THBS1, THBS2, IGFBP7, TGFBI, PCOLCE 
           NR4A1, HSPA1B, PTGS2, SPARC, IGFBP4, TIMP1, SERPINF1, FOSB, COL4A1, COL6A1 
PC_ 2 
Positive:  COL3A1, COL1A1, COL1A2, SERPINE2, HSPA1A, IGFBP7, COL6A3, FBLN1, EPCAM, RNASET2 
           IGFBP2, SPINT2, MT-CO2, MFAP4, CXCL1, CEMIP, FXYD2, TNC, CD24, IGFBP5 
           CALB1, KRT7, FOSB, CPE, SLPI, KRT19, HSPA1B, NR4A1, PDZK1IP1, TSPAN1 
Negative:  CXCL8, CSF2, MMP3, MMP1, IL6, PLIN2, IL1B, MMP10, VIM, HILPDA 
           CSF3, IER3, RRAD, SERPINB7, NMB, NEFM, SERPINB2, ADM, TM4SF1, GAPDH 
           AKR1C1, TAF1D, BTG1, EIF1, AL355607.2, GREM1, RALA, G0S2, EPB41L4A-AS1, FTL 
PC_ 3 
Positive:  PLCG2, MTRNR2L12, VIM, MTRNR2L8, LGALS1, NUPR1, COL1A1, NMB, ADAMTS1, BHLHE40 
           GADD45A, AL627171.2, GADD45B, FTL, COL3A1, CRYAB, RPS19, SNHG12, DKK1, ZFP36L2 
           SPON2, PTMA, HCFC1R1, CDKN1C, GAPDH, FBXO32, SNHG5, IER5L, KCNMA1, RPS18 
Negative:  CXCL8, IL6, CSF3, IL1B, MMP3, TFPI2, G0S2, MT2A, PTGS2, CXCL1 
           IL11, IL24, MMP1, CSF2, C15orf48, LIF, SERPINE2, FGF2, SERPINB2, CCL2 
           NRG1, STC1, IER3, GDF15, TNFAIP6, CEMIP, PLAU, INHBA, FTH1, IL13RA2 
PC_ 4 
Positive:  PLCG2, NEAT1, MT-CYB, MT-ATP6, MT-CO3, MT-CO1, MT-ND2, MT-ND5, MT-ND4, MT-CO2 
           MTRNR2L12, MT-ND3, MT-ND1, SLC5A3, MALAT1, MTRNR2L8, COL7A1, MT-ND4L, MMP3, CXCL8 
           GDF15, CSF2, IER3, AKR1B1, LINC-PINT, PLAU, MT-ATP8, CCNL2, SLC38A2, HILPDA 
Negative:  VIM, GAPDH, FTL, LGALS1, IGFBP5, FTH1, EEF1A1, NMB, HSPA1A, IGFBP3 
           TM4SF1, TMSB10, IGFBP2, SERPINE1, HSPA5, TXNRD1, ACTG1, RPL10, RPL41, EIF1 
           S100A10, ANXA1, RRAD, TIMP1, COL1A2, SERPINE2, TNFAIP6, RPS18, IGFBP6, HMOX1 
PC_ 5 
Positive:  MMP1, COL3A1, CSF2, COL1A1, MMP10, MMP3, IL1B, RRAD, COL1A2, PLAU 
           HILPDA, FOS, CXCL8, IER3, IGFBP4, SERPINB7, NEAT1, TM4SF1, SERPINB2, AL355607.2 
           DCN, SPARC, ZFP36L1, BIRC3, DPT, ID3, NEFM, ADM, ZFP36, JUN 
Negative:  HSPA5, TFPI2, SDF2L1, MANF, PDIA4, HSP90B1, CRELD2, HERPUD1, HYOU1, SERPINE2 
           GDF15, PDIA6, DNAJB11, MT2A, PLCG2, MT-ND5, FGF2, PTGS2, SEL1L, DNAJB9 
           CALR, SELENOS, HMOX1, MT-CO1, MT-CYB, NUCB2, MT-ND4, IGFBP2, SERPINE1, LIF 
2023-08-01 18:28:16 Integration 
Performing PCA on the provided reference using 1312 features as input.
Projecting PCA
Finding neighborhoods
Finding anchors
        Found 462 anchors
Filtering anchors
Error in nn2(data = c(0.116567313318016, 0.0402222983901778, -0.0560826803852252,  : 
  Cannot find more nearest neighbours than there are points
Calls: get_cellfracs_seuratv3 ... FindAnchors -> FilterAnchors -> NNHelper -> do.call -> nn2
Execution halted
Traceback (most recent call last):
  File "/home/kwang/anaconda3/envs/cytospace/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/home/kwang/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 690, in run_cytospace
    main_cytospace(**arguments)
  File "/home/kwang/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 522, in main_cytospace
    read_data(scRNA_path, cell_type_path, 
  File "/home/kwang/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 35, in read_data
    cell_type_fraction_estimation_path = estimate_cell_type_fractions(scRNA_path, cell_type_path, st_path, output_path, output_prefix)
  File "/home/kwang/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/common/common.py", line 119, in estimate_cell_type_fractions
    out = subprocess.run(run_args, check=True)
  File "/home/kwang/anaconda3/envs/cytospace/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '/home/kwang/anaconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/get_cellfracs_seuratv3.R', '--scrna-path', 'ONE_scRNA_data.txt', '--ct-path', 'ONE_cell_type_labels.txt', '--st-path', 'ONE_ST_data.txt', '--outdir', '/BiO/home/kwang/PROJECT/SCS/result/cytospace_results', '--prefix', '']' returned non-zero exit status 1.

Could you help me with this please? Many thanks.

**Comment by WubingZhang** [comment]
Hi,

Could you check the number of cells in your scRNA-seq data? I guess there are limited total number of cells or limited number of cells in a particular cell type which leads to the error in estimating cell type fractions using Seurat V3.

Best,
