### ISSUE TITLE
color label for cellTypes

### ISSUE THREAD

**Issue by abulislam** [digitalcytometry/cytospace#80]
image=("S1" "S2" "S3" "S4")

for sample in "${image[@]}"; do
  cytospace \
    --scRNA-path $sc/count_matrix.tsv \
    --cell-type-path $sc/cell_types.tsv \
    --st-path "$st/${sample}ST_data.txt" \
    --coordinates-path "$st/${sample}Coordinates.txt" \
    --output-prefix ${sample} \
    --downsample-off
done

Although I am using same reference Single-cell data, but for different spatial-transcriptomics (ST) sample/data (tissue section from same slide) (S1, S2, S3, S4) cytospace is labeling cell-types with different color for different  ST sample. How can we control the color label for each cell type so that they remain constant for every ST samples?

Thanks

**Comment by WubingZhang** [comment]
Hi,

Currently, cytospace does not support a custom color palette for plotting. However, you can easily re-plot the figures using Python scripts from https://github.com/digitalcytometry/cytospace/blob/main/cytospace/post_processing/plot.py with the cytospace output `assigned_locations.csv` as input data.

Best,
