### ISSUE TITLE
Some cell types are not inferred

### ISSUE THREAD

**Issue by fuerzhou** [digitalcytometry/cytospace#82]
Hello Cytospace Team,

Thank you for providing this amazing tool for ST data deconvolution.

The tool was successfully run on our data, and there is one issue to note. There are 14 clusters (cell types) in the scRNA data, but there are only 9 of them mapped to the ST data.

scRNA:
![Screenshot 2023-08-17 at 5 02 17 pm](https://github.com/digitalcytometry/cytospace/assets/19812186/7b433c81-da95-4857-822b-25e7ba89e271)

ST predicted:
![Screenshot 2023-08-17 at 5 00 49 pm](https://github.com/digitalcytometry/cytospace/assets/19812186/a9862755-b017-4994-9a75-9d2236de0f1e)

I did notice that Cluster 9 to Cluster 13 have cells fewer than 200, but not sure if this is the cause of the issue. Could you please provide some insights to this? 

Thank you!
Yuzhou

**Comment by WubingZhang** [comment]
Hi,

CytoSPACE uses Seurat V3 to estimate the cell type composition in the spatial data and outputs the estimation results into the Seurat_weights.txt file. I assume that the estimated cell fractions of the two clusters are 0, included in the Seurat_weigthts.txt.

Best,

**Comment by fuerzhou** [comment]
Hi @WubingZhang,

Thank you for the reply. Yes I had a look at the Seurat_weights.txt file and the 5 clusters (9-13) that are missing have estimated 0 cell fractions. However, Cluster_2 is also 0 in Seurat_weights.txt but it also has estimated proportion in some spots. Is it because the prediction of the spots is not necessarily linked to the prediction of cell fraction by Seurat?

![Screenshot 2023-08-23 at 5 15 38 pm](https://github.com/digitalcytometry/cytospace/assets/19812186/cd873893-8883-4660-b831-a1b26d6d4f25)

![Screenshot 2023-08-23 at 5 20 11 pm](https://github.com/digitalcytometry/cytospace/assets/19812186/a73b7097-29f5-4548-8d84-b90404ae8e8e)

Thank you!
Yuzhou

**Comment by fuerzhou** [comment]
Thank you very much for the answers and clarification. It makes clear sense to me now. 

Best regards,
Yuzhou
