### ISSUE TITLE
Working with Stereo-seq data

### ISSUE THREAD

**Issue by tvegawaichman** [digitalcytometry/cytospace#83]
Hello!
I'm working with Stereo-seq data, specifically with bin 50 (25-micrometer diameter per spot) from the MOSTA [dataset](https://db.cngb.org/stomics/mosta/download/). I would like to know if you recommend that I run it as if it were a single-cell ST or as a legacy ST. Additionally, if you have any information on the recommended parameters for this type of data, I would greatly appreciate it.
Thank you!

**Comment by WubingZhang** [comment]
Hi,

The MOSTA website provides segmented single-cell data. If you have segmented single-cell data, please use cytospace single-cell mode. If you want to use the bin 50 data, consider it a Visium sample and set the -mcn (mean number of cells per spot) to 4.

Best,

**Comment by tvegawaichman** [comment]
Perfect, thank you very much!
