### ISSUE TITLE
ValueError: Cell type TYPE_NA in the ST dataset is not available in the scRNA-seq dataset

### ISSUE THREAD

**Issue by suerle** [digitalcytometry/cytospace#88]
Hi cytospace team

When running

cytospace \
   --scRNA-path scRNA_data.txt \
   --cell-type-path cell_type_labels.txt \
   --spaceranger-path C1_sr_output.tar.gz \
   -sm lap_CSPR

I encounter the following error:

...
Down/up sample of scRNA-seq data according to estimated cell type fractions
Traceback (most recent call last):
  File "/Users/miniconda3/envs/cytospace/bin/cytospace", line 8, in <module>
    sys.exit(run_cytospace())
  File "/Users/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 690, in run_cytospace
    main_cytospace(**arguments)
  File "/Users/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 585, in main_cytospace
    sample_single_cells(scRNA_data_sampled, cell_type_data, cell_type_numbers_int, sampling_method, seed)
  File "/Users/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/cytospace.py", line 242, in sample_single_cells
    raise ValueError(f"Cell type {cell_type} in the ST dataset is not available in the scRNA-seq dataset.")
ValueError: Cell type TYPE_NA in the ST dataset is not available in the scRNA-seq dataset.

I don't really know where TYPE_NA in the ST dataset is coming from.
Any help appreciated.
Thank you!

**Comment by erinlbrown** [comment]
Hi, could you share the output produced by the cell fraction estimation step? This would be the `Seurat_weights.txt` file.

Best,
Erin

**Comment by suerle** [comment]
Here is the ouput:
Index	Neutrophils	Monocytes	Fibroblasts	Macrophages	DC	Endothelial cells	Stem cells	Stromal cells	Epithelial cells	NA	Mast cells	B cells, pro	Basophils	Microglia	ILC
Fraction	0.099300231	0.130926354	0.142589851	0.190923248	0.066941943	0.088922329	0.016515722	0.106688728	0.032334730	0.109446752	0.000000000	0.003691090	0.001015669	0.010703353	0.000000000
Thanks!

**Comment by erinlbrown** [comment]
It looks like the fraction estimation script is outputting an abundance prediction for cells of type "NA"; is there a cell type label missing from this list compared to what you expect? It might be that there is some issue with formatting causing the R script to label one type "NA".

**Comment by suerle** [comment]
Thanks for your feedback. Today I ran the code again successfully without the described error message. Not what went different. Anyway, thanks!
