### ISSUE TITLE
Have Docker images or singularity images?

### ISSUE THREAD

**Issue by caiquanyou** [digitalcytometry/cytospace#90]
Hello，it is a great work, and when I try to use it on other machine which install the Seurat V4, things become diffcult. So I wonder if your team could give a Docker images just for run or a dockerfike would be very thankful.

**Comment by erinlbrown** [comment]
Thank you for your comment! We do not have a Docker image produced for CytoSPACE at this time but recommend handling compatibility issues like you describe by installing CytoSPACE in a conda environment of its own using the provided environment .yml file.
