### ISSUE TITLE
can i get the simulated dataset?

### ISSUE THREAD

**Issue by jennyxxxxxx** [digitalcytometry/cytospace#91]
Hi, i am excited with your work. I want to know something.Is the simulation data set included in the data availability given in the paper? And how is this simulation data generated? Which part of the data set is the simulated data？Can this simulation data be used in other deconvolution tools？

**Comment by erinlbrown** [comment]
Hi, thank you for your message! The simulation data is available upon email request, and details of the simulation data and its generation are included in the "Simulation framework" Methods section here: https://www.nature.com/articles/s41587-023-01697-9. The simulation data should be sufficiently general that it could be used with any other deconvolution tool that would be applied to Visium data, legacy ST data, or similar.

**Comment by caiquanyou** [comment]
Hi, very useful tool and i also request for the simulated dataset to test the detail different among other method , could you please send the data?

**Comment by erinlbrown** [comment]
Thank you! For data request, please reach out via email and we can share.
