### ISSUE TITLE
Any plans on updating working Python version?

### ISSUE THREAD

**Issue by andrew-weisman** [digitalcytometry/cytospace#92]
environment.yml utilizes Python v3.8 which is getting pretty old. Any plans in the near future for testing this package working with newer versions of Python? Thanks!

**Comment by erinlbrown** [comment]
Thanks for your question! We do plan to update the Python version dependency for this package, probably within the next 3-6 months.

**Comment by andrew-weisman** [comment]
Sounds good, thanks Erin!
