### ISSUE TITLE
Guide post cytoSPACE

### ISSUE THREAD

**Issue by xiweiwu** [digitalcytometry/cytospace#93]
Thank you for developing such a wonderful tool. I have run CytoSPACE successfully on Visium data. I would like to create either a Seurat or SingleCellExperiment object using the assigned_expression and assigned location information for further analysis, such as plotting and CellChat. I am having trouble creating a Seurat object using the output, as the number of data points have increased from original Visium spots, and new higher resolution spot locations need to be defined. Is there a guide how to do that? Thanks.

**Comment by erinlbrown** [comment]
Thank you for your question and your interest in CytoSPACE! Unfortunately, we do not currently have a guide prepared for creating Seurat or SingleCellExperiment objects from CytoSPACE outputs, but we will consider this for future updates. For plotting results, you can try using or modifying the plot.py code from the CytoSPACE package.

**Comment by xiweiwu** [comment]
Thanks for the reply. I think I should be able to get the plotting part working with some tweaking. However, CellChat will be more challenging. It will be nice to have future implementation to convert the output to standard data format, such as Seurat or SingleCellExperiment.
