### ISSUE TITLE
Is there a way to plot a specific celltype alone?

### ISSUE THREAD

**Issue by NicolaasVanRenne** [digitalcytometry/cytospace#96]
Hello, 

I got cytospace to work on my data; I was just wondering if there was a command to get a cell_type_assignments_by_spot_jitter.png (single cells mapped to tissue by cytospace) for each individual celltype

I mean plotting only T cells, B cells, etc (if 'T cell', 'B cell' etc. is an annotation used for input) in a separate image output. Would be of great help!

thank you

**Comment by erinlbrown** [comment]
Hi, 

We do not currently have such a function included with the CytoSPACE package but this is something we could include for a future release. Thank you for your suggestion!

Best,
Erin
