### ISSUE TITLE
Cell Fraction estimation for Legacy ST with Smart-seq single-cell

### ISSUE THREAD

**Issue by sahil-sahni** [digitalcytometry/cytospace#97]
I noticed when working with smart-seq scRNA-seq, a previously estimated cell-fraction abundance is recommended. How does one generate cell fraction estimation for the cell-type of interest from spatial legacy data like the one you provided (Thrane_2018) in your github?

**Comment by erinlbrown** [comment]
CytoSPACE's internal cell fraction abundance estimation is implemented in get_cellfracs_seuratv3.R and relies on Seurat integration. The general process is still suitable for Smart-Seq data, but the script applies SCTransform() to the inputs expecting counts. For non-count data (e.g., TPM), I would recommend modifying get_cellfracs_seuratv3.R to replace the SCTransform() line with the [equivalent log-normalization process](https://satijalab.org/seurat/archive/v3.2/pbmc3k_tutorial): Seurat's NormalizeData() followed by FindVariableFeatures() and then ScaleData(). With default parameters, this would mean replacing line 65 with the following:

`scrna <- NormalizeData(scrna) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()`

**Comment by sahil-sahni** [comment]
Thank you! so if my smart-seq file is in counts, I can use get_cellfracs_seuratv3 without modification?

**Comment by erinlbrown** [comment]
Since you have counts and not TPM or similar, you can choose whether or not to run the script as-is. In general, SCTransform() was designed for UMI-based counts so for Smart-Seq you might consider using NormalizeData() instead, but I know some people do prefer to use SCTransform() even for non-UMI-based counts. As this is more related to the Seurat integration pipeline, I'm not sure I can provide a definitive recommendation. There's some discussion [here](https://github.com/satijalab/sctransform/issues/94) you might find helpful!

Similarly, downsampling may be more useful for UMI-based counts, but may still have utility otherwise. I'll note that in our testing, we found the core CytoSPACE algorithm to be robust to moderate variation (both in terms of noise in gene expression and with regard to input cell type fractions), so I would expect you should get similar results either way.

I'm not immediately sure the cause of your error you report - can you check how many cells of each type you have in your scRNA-seq dataset?

**Comment by sahil-sahni** [comment]
Yes! What is the minimum cell? These are the cells I have less than 200
Fibro           61
Endo          87
Macro      124
NK            44
DC1            9
DC2        26

**Comment by erinlbrown** [comment]
Probably this is too few cells for SCTransform() to work well--I would recommend using NormalizeData() then instead. I'll note also that this could be borderline on the number of cells for distinguishing DC1/DC2 well for fraction estimation, so you might check the cell fraction estimate outputs to confirm they seem reasonable.

**Comment by sahil-sahni** [comment]
Hi Thank you! But the error seems to arise when I call for the spatial transcriptomics data in line 26 and run SCTransform. The spatial transcriptomics data is from Legacy ST (Thrane et al 2018). The same data posted in the tutorial

**Comment by erinlbrown** [comment]
I see, sorry I missed that with your previous message! In that case, I'm not sure what could be the problem--can you confirm that the input file format is correct?

**Comment by sahil-sahni** [comment]
Hi yes! The format is correct. I also tried using the example spatial data that is provided in the ST Legacy folder and it didn't work.

**Comment by erinlbrown** [comment]
I see, I'm glad the modification worked but surprised there was an issue with the ST data! I'll try to replicate this. Would you mind sharing the run command you used originally?

**Comment by sahil-sahni** [comment]
is there a email I can send the script via

**Comment by erinlbrown** [comment]
Yes, please send to cytospaceteam@gmail.com

**Comment by 26huangxu** [comment]
> Thank you! so if my smart-seq file is in counts, I can run the script without a pre provided cell fraction estimation? And do I need to specify downsampling--off Additionally, when I run the above code I am getting this error:
> 
> Error in split.default(x = cells.vector, f = ceiling(x = seq_along(along.with = cells.vector)/ncells)) : group length is 0 but data length > 0 Calls: get_cellfracs_seuratv3 ... SCTransform -> SCTransform.StdAssay -> split -> split.default In addition: There were 50 or more warnings (use warnings() to see the first 50) Execution halted

> Thank you! so if my smart-seq file is in counts, I can run the script without a pre provided cell fraction estimation? And do I need to specify downsampling--off Additionally, when I run the above code I am getting this error:
> 
> Error in split.default(x = cells.vector, f = ceiling(x = seq_along(along.with = cells.vector)/ncells)) : group length is 0 but data length > 0 Calls: get_cellfracs_seuratv3 ... SCTransform -> SCTransform.StdAssay -> split -> split.default In addition: There were 50 or more warnings (use warnings() to see the first 50) Execution halted

I also had the same error,would you tell me how you solved this problem?
