### ISSUE TITLE
Running cytospace with multiple slides

### ISSUE THREAD

**Issue by sharonlee7980** [digitalcytometry/cytospace#98]
I was wondering if there were any ways for CytoSPACE to incorporate information about multiple slides/samples.
I’m currently analyzing three different samples, each with separate snRNA-seq data. 

When I run the code, cell_type_assignment_by_spot shows those three samples overlapping with each other. They don’t completely overlap, so it seems like the number of cells in each spot doesn’t fully incorporate the actual spatial coordinate information. For example, if dentate nuclei are in spot(0,1) in one sample and the other two samples also have dentate nuclei in the same spot, since the samples overlap slightly off of each other, I believe that spot for dentate nuclei is being read as (0,1), (0,5), (0,9). Therefore, the number of cells per spot doesn’t show the actual location (level) of that specific cell.

My ultimate goal is to see those three samples separately for each cell type in one image, in which different cell types are color-coded.

Thanks!

**Comment by savagyan00** [comment]
Thank you for using CytoSPACE and for reaching out. To better understand the issue you’re encountering and offer precise support, it would be helpful if you could provide some more information.

In particular, could you describe the ST data samples you’re working with? What ST platform, and are they sequential slides from the same tissue sample or expression from multiple layers? Relatedly, could you describe more what you mean by CytoSPACE showing the samples overlapping and about the spot coordinates? It might help to share the outputs you get, highlighting where you see an issue and what you anticipated seeing instead. If you prefer, you can email [cytospaceteam@gmail.com](mailto:cytospaceteam@gmail.com) with this as well.

In general, while it is possible for users to perform their own integration across CytoSPACE results, the tool does not internally support an integrated analysis of multiple samples. 

Thank you!
