### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [digitalcytometry/cytospace#99]
Hi, I'm trying to install CytoSPACE, but I keep getting dependency issues:

Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - datatable=0.11.1*
  - bioconductor-glmgampoi

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/bioconda/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

Using bioconda or mamba doesn't work either. Using a fresh installation on both miniconda and new environment

**Comment by erinlbrown** [comment]
Hi,

Thank you for your interest in CytoSPACE, and sorry you’re running into these dependency issues! I suspect this is a platform-related issue–it seems some of the conda channels may only have Mac and Linux versions up to date. Could you try the following steps?

- Check if there is a broken environment already initialized from the previous installation attempts - run `conda env list` and if cytospace_v1.1.0 is listed, make sure the environment is deactivated and then run `conda remove -n cytospace_v1.1.0`
- Remove the lines for these two packages (lines 12 and 20) from your environment.yml file and repeat step 4 of the CytoSPACE installation instructions ,`conda env create -f environment.yml` 
- Activate the conda environment, `conda activate cytospace_v1.1.0`
- Install datatable via pip instead, `pip install datatable`
- Open an R session in the command line and run 
```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("glmGamPoi")
```
- Then exit R, and resume the CytoSPACE installation instructions at step 6 (`pip install .`)

Please let us know if this works–we’ll update the documentation to provide a better solution for Windows users if so, and happy to help troubleshoot further if not.
